version: ''

services:
#  db:
#    image: postgres:12
#    ports:
#      - "5432:5432"
#    restart: always
#    environment:
##      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
##      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
##      POSTGRES_DB: alphastock
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: alphastock
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    networks:
#      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
#    depends_on:
#      - db
    ports:
      - "8081:8080"
    environment: #Pass environment variables to the service
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cmjtvqnqd2ns73bm181g-a.oregon-postgres.render.com/alphastock_5nw2
      SPRING_DATASOURCE_USERNAME: alphastock_5nw2_user
      SPRING_DATASOURCE_PASSWORD: CECyE2NQsR6x55dMM3skOj7Y36WupRgs
      APIKEY: ${APIKEY}
    networks:
      - backend
#volumes:
#  pgdata: {}

networks:
  backend: