version: '1'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: alphastock
#      MYSQL_USER: root
      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
#    restart: always
    environment: #Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/alphastock?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      APIKEY: BAU3BSCD2OT8V1XP

volumes:
  db-data: